In [1]:
import numpy as np

In [18]:
data = np.loadtxt('./students.csv',delimiter=",", skiprows=1)
print(data)

[[ 1. 78. 85. 69.]
 [ 2. 92. 88. 91.]
 [ 3. 65. 70. 72.]
 [ 4. 88. 90. 84.]
 [ 5. 55. 60. 58.]]


In [9]:
maths = data[:,1]
physics = data[:,2]
chemistry = data[:,3]
print(maths,physics,chemistry)

[78. 92. 65. 88. 55.] [85. 88. 70. 90. 60.] [69. 91. 72. 84. 58.]


In [10]:
print(np.mean(maths),np.mean(physics),np.mean(chemistry))

75.6 78.6 74.8


In [16]:
Topper_student_marks = np.max(np.sum(data,axis=1))
print(Topper_student_marks)

273.0


In [23]:
avg_marks = np.mean(data[:,1:],axis=1)
print(avg_marks)

[77.33333333 90.33333333 69.         87.33333333 57.66666667]


In [37]:
Grades = np.array(["","","","",""])
Grades[avg_marks>=85]="A"
Grades[(avg_marks>=70) & (avg_marks<85)]="B"
Grades[(avg_marks>=55) & (avg_marks<70)]="C"
Grades[avg_marks<55]="D"


In [38]:
print(Grades)

['B' 'A' 'C' 'A' 'C']
